### ISSUE TITLE
JAWS reads Angular code

### ISSUE THREAD

**Issue by m80her** [FreedomScientific/VFO-standards-support#107] opened 2018-08-30 16:43 UTC
### Summary

> In a AngularJS application, JAWS reads the pre-compiled HTML content instead of the compiled HTML content. For instance, if I have the following HTML:
> 
    <li ng-repeat="item in items">{{item.name}}</li>

### Expected result

> If a new element that looks like `{name: 'Widget x'}` is added to `items`, expected result would read "Widget x".

### Actual result

> JAWS reads "left brace left brace item dot name right brace right brace".

### Example

> [plunkr using snapshot version of Angular](http://plnkr.co/edit/Zpo9AjbjAaO4hsPcvjyv?p=preview)

### Additional Information

>  this is a copy of the issue raised here https://github.com/angular/angular.js/issues/15079 

#### JAWS version and build number

> 2018.1808.10 ILM Professional Edition
 
#### Operating System and version

> Windows 10 Pro, v1709, build 16299.309

#### Browser and version:

> IE11, v11.309.16299.0, 11.0.56

**Comment by stevefaulkner** [comment] 2018-08-31 17:55
@m80her I can reproduce. Will file a bug on JAWS internally

**Comment by stevefaulkner** [comment] 2018-08-31 18:32
filed- Bug 103329: JAWS Reading Precompiled HTML content in an AngularJS  Application

**Comment by akegan** [comment] 2019-10-01 17:27
I'm running into this issue with my AngularJS application and JAWs as well. Is there an update on the internally-filed bug?

**Comment by corinnaSchultz** [comment] 2019-10-01 18:28
Maybe a workaround could be to wrap the entire page in an aria-live region so when Angular updates things, JAWS will notice?

**Comment by JAWS-test** [comment] 2019-10-01 19:51
> Maybe a workaround could be to wrap the entire page in an aria-live region so when Angular updates things, JAWS will notice?

theoretically `aria-busy=true` should help. When all updates are done, the page will be set to `aria-busy=false` and JAWS will start evaluating the updated content: https://www.w3.org/TR/wai-aria-1.1/#aria-busy

**Comment by JAWS-test** [comment] 2019-10-04 05:32
* The cause of the problem is that first the angular code is inserted into the live region, this leads to the output of the code, and only then the code is replaced by the text. 
* The problem does not occur in Firefox and Chrome. Why is it unclear to me.
* aria-busy will theoretically help here, unfortunately aria-busy doesn't work correctly in IE 11 (https://github.com/FreedomScientific/VFO-standards-support/issues/257). I.e. the only solution would be to insert the text in live regions instead of code.

**Comment by TPGJRogers** [comment] 2022-09-30 18:31
Issue is marked IE11. Closing.

**Closed by TPGJRogers** 2022-09-30 18:31 UTC
Labels: JAWS bug filed, IE11, JAWS bug
