### ISSUE TITLE
Firefox 64.0 + Links List shows link text instead of its aria-label

### ISSUE THREAD

**Issue by poohthewinnie** [FreedomScientific/VFO-standards-support#158] opened 2019-01-03 12:07 UTC
### Summary

1. In Firefox 64.0, go to https://jsbin.com/wotovutuwi/1/edit?html,output
2. Open JAWS 2018 Links List (Insert+F7)

### Expected result

Aria-labels are listed: "Report for Jon Doe" and "Report for Jane Doe"

### Actual result

Links text is in the list: "First Report" and "Second Report"

### Example

https://jsbin.com/wotovutuwi/1/edit?html,output

#### JAWS version and build number
JAWS Version 2018.1811.2 ILM

#### Operating System and version
Windows 10 Enterprise

#### Browser and version:
Mozilla Firefox 64.0 (64-bit)

**Comment by TestPartners** [comment] 2019-01-04 16:16
The issue is not just with the Links List. When reading the page with JAWS 2018.1804.26 ILM and Firefox 63, the following behaviours occur:

When tabbing between the links, JAWS announces the "aria-label" attribute.
When "arrowing" between the links using virtual cursor, JAWS announces the link text.

By contrast, in Internet Explorer 11, Edge 17 and Chrome 71, JAWS announces the "aria-label" attribute regardless of the method of navigation. Also, the Links List contains the "aria-label" attribute in all these browsers.

**Comment by scottaohara** [comment] 2019-03-06 14:45
Reviewing the provided test case:

Confirmed bug with JAWS 2018 and Firefox 65.0.2.  

Can no longer reproduce the issue with JAWS 2019.1901.66 and Firefox 65.0.2.

**Comment by scottaohara** [comment] 2019-03-06 16:32
Closing as this issue has been fixed per verifying with JAWS 2019

**Closed by scottaohara** 2019-03-06 16:32 UTC
