### ISSUE TITLE
Jaws 18 is reading as no table found in Windows 10

### ISSUE THREAD

**Issue by abhilash-kokala** [FreedomScientific/VFO-standards-support#92] opened 2018-06-20 06:29 UTC
Jaws 18 is not recognizing the Tables in the DOM and when using the short cuts to find the table Jaws mentions that no table found.

This behaviour is inconsistent. Some of the tables it is reading though the HTML generation code is same.

**Comment by JasonAment** [comment] 2019-04-30 23:37
@abhilash-kokala - Could you please provide more information:
1. Does this happen in all browsers?
2. Is there a code sample that we could reference? If not, could you please provide a website where you encounter the issue?

**Comment by JasonAment** [comment] 2019-05-01 04:02
Closing as a duplicate of #124 "Jaws misidentifies a table as a display table"

**Closed by JasonAment** 2019-05-01 04:02 UTC
Labels: duplicate
