### ISSUE TITLE
role=combobox does not work

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#221] opened 2019-07-16 06:07 UTC
### Summary

role=combobox does not work

1. https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html 
2. tab to the combo box, read with arrow keys, navigate with E and C and look at the entries in the element lists (CRTL+INS+C, CTRL+INS+E)

### Expected result

1. role=combobox is output with a separate role (distinguishable from input fields and select elements, although the specification unfortunately defines the same role for some select elements and combo boxes, which is an error)
2. label is output correctly
3. you can navigate through the list entries
4. the list entries are output correctly

### Actual result

No browser meets all requirements.

The incorrect output is problematic because the html combobox element (input list=, datalist) is not output correctly (https://github.com/FreedomScientific/VFO-standards-support/issues/218), so that there is no possibility for the two Microsoft browsers to implement combo boxes. Combo boxes are very common on the web and most frameworks use them instead of select elements.

With the change from ARIA to ARIA 1.1 the specification for role=combobox has changed. However, the 1.0 implementation doesn't work at all in Internet Explorer 11 either. According to the old specification there were several ways to implement role=combobox - none of them led to correct output with IE 11 and JAWS.

#### IE 11 

* Tab: Focus remains on previous interactive element (link "ARIA 1.0 Combobox Without Autocomplete"), this element is output and operated. I.e. the operation of the combo box is not possible. However, the problem only occurs if JAWS was not in Forms mode for the previous item. For example, if there was no link in front of the combo box, but an input field, the role will be output correctly (even if the rest of the output is a bit faulty).
* linear reading with arrow keys: 3-4 x "combo edit reduced listbox", value only at 2nd (at example 3 additional "button" is output). If the form mode is activated with the Enter key, the focus is not in the form field and therefore the combo box cannot be operated in this way either.
* C, E, B: "combo edit reduced listbox", without label
* CTRL+INS+E: "edit combo" (without value and label)
* CTRL+INS+C: 3 empty entries (no label, role, value)

#### Edge

* Tab: label and "edit"
* linear reading: 3-4 x "combobox reduced", without value
* INS+F5: 2 to 3 elements per combobox in the list: 
	* "combobox" without label, 
	* "edit" with label, without value, 
	* button (example 3)
* C, E, B: "combobox reduced" (without label and value)

#### Chrome, Edge (Chromium)

* Tab: ok
* linear reading: ok
* CTRL+INS+E: "combo edit" without label and value
* CTRL+INS+C: value, but no role and label (empty if there is no value)
* C, E: no label

#### Firefox, Firefox ESR:

* Tab: ok
* linear reading: value and "combo edit has popup listbox"
* C, E: "combo edit has popup listbox" and value, no label
* CTRL+INS+E: "combo edit" without label and without value
* CTRL+INS+C: value, but no role and label (empty if there is no value)

### Example

see above

#### JAWS version and build number

JAWS 2019.1906.10
The problems occur analogously with older versions of JAWS (JAWS 13, 14, 15, 16, 17, 18, 2018).
 
#### Operating System and version

Windows 10, Windows 8

#### Browser and version:

Internet Explorer 11.0.9600.19400
Chrome 75.0.3770.100
Edge  41.16299.1004.0
Edge 77.0.211.3 (Chromium)
Firefox 68.0
Firefox ESR 60.8.0

**Comment by Indimeco** [comment] 2019-10-05 00:17
Hello,

I conducted an independent investigation and was about to raise this same issue until I saw this.
My findings are an *exact* match with yours and I can confirm them!
I'll attach some links and what additional information I have for the convenience of others.

The examples on the given test page are following [the specification for comboboxes provided in WAI-ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#combobox).

It is my assumption that the defects are a result of [changes to the combobox usage between the WAI-ARIA 1.0 spec and the WAI-ARIA 1.1 spec](https://www.levelaccess.com/differences-aria-1-0-1-1-changes-rolecombobox/).

If you move the ```role="combobox"``` onto the ```<input>```, in the fashion of the 1.0 spec, **then JAWS will enter forms mode as expected and the component will function normally on IE11**. 

A similar behavior can be observed on [this example page](http://juicystudio.com/tpg/rbc/wrappedcombo/combo.html) linked via the VFO aria roles page IF you remove the ```role="application"``` from the outermost ```<div>```.

**Comment by JAWS-test** [comment] 2019-10-05 03:13
> It is my assumption that the defects are a result of changes to the combobox usage between the WAI-ARIA 1.0 spec and the WAI-ARIA 1.1 spec.

My test gave me different results. Also the ARIA 1.0 pattern never worked with IE 11. There were implementation variants, which under certain circumstances led to a correct output, but never worked reliably. For example, with some 1.0 patterns, the tab navigation output was correct when JAWS was already in forms mode (due to the previous element), but not correct when JAWS was not in forms mode. Or the output was correct when reading with the arrow keys, but not when navigating with the Tab key. I myself have built and tested many different patterns with role=combobox and there was never a variant that worked in IE 11 with JAWS.

**Comment by Indimeco** [comment] 2019-10-05 20:42
Thank you. Admittedly I am only a novice SR user and did not deeply test the 1.0 pattern, only observed it was entering forms mode where the 1.1 pattern was not.
You have saved me lots of time and effort tinkering.

**Comment by btitovconcise** [comment] 2020-05-26 09:24
**Summary**

JAWS doesn't read current value of input in IE using TAB.

We have the combobox with behaviour similar to [this](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html) example.

In IE JAWS doesn't read current value of combobox input using TAB, but read it using ARROWS.
For example, in Chrome this problem doesn't exist.

This problem also was mentioned by @JAWS-test:
> Or the output was correct when reading with the arrow keys, but not when navigating with the Tab key.

**Steps to reproduce**
1. Open [example](https://www.w3.org/TR/wai-aria-practices-/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html) in IE.
2. Read combobox in example using TAB.

**Expected behaviour**
JAWS should read value of input using TAB in IE.

**Actual behaviour**
JAWS doesn't read value of input using TAB in IE.

**Example**
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html.

**Additional Information**
IE version: 11.836.18362.0
JAWS version: 2020.2004.66
Windows 10.

**Comment by lamador** [comment] 2020-06-15 17:49
Duplicate of #167 and #166.

Although in draft status, consider using the APG 1.2 combobox instead as it is a more stable pattern across the board than the one used in APG 1.1.

**Closed** 2020-06-15 17:52 UTC
Labels: Solution provided

**Comment by JAWS-test** [comment] 2020-06-16 04:45
@lamador 

I do not agree at all that the ticket is simply closed with reference to the new APG 1.2 example:
1. APG 1.2 is currently only a working draft and not a recommendation
2. The examples in APG 1.2 should have been tested with JAWS if they were to be the solution 

The fact is that IE 11 and Combobox did not work with any version of JAWS between 13 and the current one (2020.2004), regardless of whether I take the example from APG 1.0, 1.1, or 1.2. 

But the combo box does not work perfectly in Chrome either. For example, in the element overview (INS+Ctrl+C) the value and role are not displayed.

It should also be noted that according to the ARIA specification, the APG 1.0 example must continue to work: "User agents, assistive technologies, and conformance checkers SHOULD continue to support the ARIA 1.0 pattern so that existing implementations of the ARIA 1.0 pattern remain functional." https://www.w3.org/TR/wai-aria-1.2/#combobox.

Besides, my ticket is not a duplicate. The other two tickets describe only small partial problems, whereas I have summarized all known problems.

**Comment by scottaohara** [comment] 2020-06-16 11:23
As this ticket is introduced as being about results from testing the ARIA 1.1 combobox pattern, it's very much appropriate for @lamador to have closed the ticket and referenced the coming ARIA 1.2 WD pattern.  

If you would like to open a ticket about the 1.0 pattern specifically, and/or the 1.2 pattern specifically, then please do so.  But a general ticket about combobox and then listing out all issues, that require potentially different solutions for the different patterns, and where some of the issues are browser-based and not necessarily a fault of JAWS, is entirely too broad.

Also note, that the ARIA 1.2 WD you quote says user agents/AT 'SHOULD' continue to support ARIA 1.0 pattern, not "must".  While I don't pretend to assume that any user agent / AT is waiting to drop support for the 1.0 pattern, it is worth noting that a 'SHOULD' means that it will have lower priority in support than the 1.2 expectation.  Especially for browsers like IE11, where JAWS has to put in significantly more effort to resolve issues that are commonly due to the poor accessibility support/implementations of that browser.

**Comment by JAWS-test** [comment] 2020-06-16 13:18
@scottaohara 
"Solution provided" is incorrect if it has not been checked whether the "solution" (APG 1.2) works at all. It's not doing it. I will open a ticket if Freedom Scientific still supports IE 11 at all. If not, no ticket is necessary. Can you please tell me if JAWS will still support IE 11?

**Comment by scottaohara** [comment] 2020-06-16 14:17
@JAWS-test please feel free to open an issue(s) concerning ARIA 1.0 and/or ARIA 1.2 comobobox pattern support. The current 'solution' for the ARIA 1.1 pattern is to advise against using it, as while other alternatives may not have full support either, at least they will be worked on.  

However, as it is not a fully robust solution, I have removed the "solution provided" label to hopefully mitigate any confusion here.
