### ISSUE TITLE
Link is read multiple times when it is in a list

### ISSUE THREAD

**Issue by ghristanov** [FreedomScientific/VFO-standards-support#13] opened 2017-10-20 13:14 UTC
### Summary

1. Go to https://codepen.io/anon/pen/NaJaPr
2. Navigate through the elements

### Expected result

Each of the links is read only once.

### Actual result

Only the link outside the list is read once. In IE, both JAWS 16 and JAWS 18 have troubles reading the link when it is located inside a list. The first link in a given list item, then the other content inside that item and finally the same link again is read.

### Example

https://codepen.io/anon/pen/NaJaPr

#### JAWS version and build number

18.0.2945, 16.0.4474
 
#### Operating System and version

Windows 10 Enterprise 10.0.10586 Build 10586

#### Browser and version:

Internet Explorer 11

**Comment by stevefaulkner** [comment] 2017-10-20 13:37
Confirmed behavior with IE11 + JAWS 18.0.453 + Win 10

**Comment by stevefaulkner** [comment] 2017-10-21 10:27
I created a slightly cleaned up pen https://codepen.io/stevef/pen/EwMwMJ
**note:** the issue occurs when the links are tabbed to, not when using virtual cursor keys.

**Comment by stevefaulkner** [comment] 2017-11-16 16:20
@ghristanov when testing further I noticed you have `role=application` on the `body` element. When this is used the issue no longer occurs. what is the use case for `role=application` on the body element?

**Comment by LJWatson** [comment] 2017-11-22 09:03
@ghristanov Jaws (and other Windows screen readers that use a virtual buffer) [do not work with JavaScript shortcuts](https://tink.uk/time-to-revisit-accesskey/). The screen reader intercepts the keystroke before it reaches the browser (and consequently the JavaScript).

The application role forces the screen reader to stop intercepting the keystrokes, passing them straight through to the browser instead. although it makes the JavaScript shortcuts functional with Windows screen readers, it also strips the screen reader of all its native ability to naviate and interact with content.

**Comment by stes-acc** [comment] 2017-12-14 14:59
@LJWatson it is not about shortcuts. It is about JS keyhandler code for usage of complex controls with ARIA roles that have implemented **good and tested separate keyboard support with JS** for navigation and interaction.  Screen readers should disable their keyboard hooks when encountering those but reality shows that this ain't working reliably. So role=application is needed as a workaround. As soon as a proved and confirmed study out there that for all interactive ARIA roles screen readers won't interfere with JS key handlers we gracefully skip role=application. But as of today, we still need it.

**Comment by stes-acc** [comment] 2017-12-14 15:28
As an addendum, the fix of @stevefaulkner just removes the side effects of an incorrect screen reader behaviour that shold NOT be affected by presence of role=application by any means. Fixing screen reader issues by removing valid metadata or even valid host language attributes should not be the way to go. Instead, screen reader should contain fixes to avoid redundant speaking for such scenarios.

**Comment by frex65** [comment] 2020-05-18 14:10
Tested using JAWS 2020.2004.06 and confirmed to be still an issue

**Comment by BenKeyFSI** [comment] 2020-08-25 20:28
The following samples demonstrate this issue.

- [Link is read multiple times when it is in a list - Original Example from Georgi Hristanov](https://codepen.io/TPG/debug/d7397c3032ae453f066b0b7f82430039)
- [Link is read multiple times when it is in a list - Updated Example from Steve Faulkner](https://codepen.io/TPG/debug/5780ffdeb4f28d139701ef003789491e)

These URLs will still work in Internet Explorer.

**Comment by BenKeyFSI** [comment] 2020-08-25 20:44
Reported as Bug 116346 {Link text is spoken multiple times when the link is contained within a list item that is contained within an application}.

**Comment by BenKeyFSI** [comment] 2020-08-26 13:45
Technically the current behavior of JAWS is correct.

JAWS supports the concept of a container object. For a control that is contained within a group box, the container object is the group box. For a link contained within a list item the container object is the list item.

When JAWS detects a container object that is deemed to be contextually important, JAWS will speak information obtained from the container object before speaking information obtained from the object itself.

In the case of a link contained within a list item, the name of the container object is the text displayed within the list item, which just happens to include the link text. The name of the link is the link text.

JAWS is speaking the container name followed by the object name. Since the container name just happens to include the object name in this case this results in perceived repetition.

In other words, what JAWS is speaking is as follows.

    "${ContainerName} ${ObjectName} ${ObjectType}"

Thus three completely different concepts are being spoken.

The perceived repetition is occurring due for the following reasons.

* If the list item contains the link without any additional content, the ${ContainerName} is equal to the ${ObjectName}.
* If the list item contains the link along with additional content, the ${ObjectName} is included in the ${ContainerName}.

That said, the perceived repetition is annoying. Therefore, this bug is being fixed by modifying JAWS to avoid this perceived repetition. If the ${ContainerName} is equal to the ${ObjectName} or the ${ObjectName} is included in the ${ContainerName} the ${ObjectName} will not be spoken.

The end result will be as follows.

* If the list item contains the link without any additional content, only the link text will be spoken, followed by the type.
* If the list item contains the link along with additional content, the list item text will be spoken, followed by the type.

Note that having JAWS only speak the link text in this case would not be appropriate. This would mean that the container name is not being spoken.

**Comment by BenKeyFSI** [comment] 2020-08-28 14:46
After discussing this issue with Brett Lewis and Glen Gordon we decided that the best solution is to modify JAWS so that it does not speak container information in the link has a list item parent case.

**Comment by BenKeyFSI** [comment] 2021-01-11 21:39
A fix for this bug is available in JAWS 2021. It was first available in 2021.2009.19.400.

Thus I am closing this issue.

**Closed by BenKeyFSI** 2021-01-11 21:39 UTC
Labels: IE11, bug
