### ISSUE TITLE
Additional content within Groups read out by JAWS in Chrome Browser

### ISSUE THREAD

**Issue by mlhulek** [FreedomScientific/VFO-standards-support#507] opened 2021-03-10 09:08 UTC
### Summary

The issue occurs in Chrome Browser with JAWS 2021. In the example you will notice that JAWS reads out additional content of the group before actually announcing the focused element. I use [TAB] to navigate to the input field.

https://codepen.io/mlhulek/pen/qBqQKya

### Expected result

**JAWS 2021 in Firefox:**

Group 0 
Label 1 Edit Has Popup
Date
Type in text.

**NVDA in Chrome:**

Group 0  grouping
Label 1   edit  subMenu  Date

### Actual result

**JAWS 2021 in Chrome:**

Group 0 group
**Button 1 Button 2 More Text** 
Label 1  Edit Has Popup
Date
Type in text.

### Example

https://codepen.io/mlhulek/pen/qBqQKya

#### JAWS version and build number
JAWS 2021.2102.34
 
#### Operating System and version
MS Windows 10 Enterprise
Version 10.0.18363 Build 18363

#### Browser and version:
Chrome Version 89.0.4389.72 (Official Build) (64-Bit)

**Comment by JAWS-test** [comment] 2021-03-10 10:13
This is a problem, because tabindex=-1 should not lead to incorrect output. The only question is whether JAWS or Chrome is responsible for the problem. Because Chrome passes elements with tabindex=-1 as grouping elements (and their text content as label) to the Accessibility API.

I am in favor of reopening the ticket

**Comment by mlhulek** [comment] 2021-03-10 10:17
Thanks for the feedback, let's reopen the ticket. It would be great if there was a solution besides removing tabindex="-1" (in Chrome with JAWS 2021).

**Comment by JAWS-test** [comment] 2021-03-11 14:48
Sorry, is probably a duplicate of https://github.com/FreedomScientific/VFO-standards-support/issues/497 and can therefore be closed

**Comment by mlhulek** [comment] 2021-03-12 07:00
I will close this ticket as it is handled in #497. Thanks.

**Closed** 2021-04-07 12:43 UTC
