### ISSUE TITLE
JS alert and confirm message is not output  (Chrome)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#361] opened 2020-01-27 13:14 UTC
### Summary

* Go to https://codepen.io/jaws-test/pen/JjoVKvp
* Activate the buttons

### Expected result

Javascript message (with alert or confirm command) is output

### Actual result

Message is not output 

The problem occurs only in Chrome+JAWS and not in IE or Firefox. It also occur with NVDA+Chrome.

The problem does not occur with a prompt message

#### JAWS version and build number
JAWS 2019
 
#### Operating System and version
Windows 10

#### Browser and version:
Chrome 79.0.3945.130

**Comment by ferllings** [comment] 2020-05-20 14:04
Duplicate of #351

**Closed by ferllings** 2020-05-20 14:04 UTC
Labels: duplicate
