### ISSUE TITLE
JAWS says "hypertext"

### ISSUE THREAD

**Issue by brooksr1** [FreedomScientific/VFO-standards-support#170] opened 2019-01-30 01:15 UTC
jj### Summary

> Brief description of the issue. Please list any specific steps.
1. Open a form in Microsoft Access in tabular mode.
2. Use the right and left arrow keys to move between fields on a row.
### Expected result
Expect JAWS to say the data in the field.

### Actual result
JAWS says the data in the field, followed by saying "hypertext".

### Example

Instead of saying "radiologist", JAWS say "radiologist  hypertext"

### Additional Information

The textboxes do have a hypertext property, but they are all set to NO.

#### JAWS version and build number

JAWS 16.0.4474
 
#### Operating System and version

Windows 10 Home, 10.0.17 134 Build 17134

#### Browser and version:

Firefox Quantum 64.0.2

**Comment by lamador** [comment] 2020-06-15 13:40
@brooksr1 please provide a code sample of the issue.

**Comment by brooksr1** [comment] 2020-06-15 14:34
I believe this is from over a year ago!

**Comment by lamador** [comment] 2020-06-15 21:10
Apologies for the delay in responding. Is the issue browser-based or within the MS Access app?  If the former, a code sample is necessary to text the issue described.  If the latter, then the issue is out of scope for this support site and suggest contacting [Freedom Scientific Technical Support](https://support.freedomscientific.com/About/ContactUs).

**Comment by frex65** [comment] 2023-02-21 16:18
No response since June 2020 - closing and archiving

**Closed by frex65** 2023-02-21 16:18 UTC
Labels: More info needed, archive
