### ISSUE TITLE
Jaws does not enter application mode when focus is moved inside a container with role="application"

### ISSUE THREAD

**Issue by tydunkel** [FreedomScientific/VFO-standards-support#93] opened 2018-06-20 17:18 UTC
### Summary
When focus is programmatically moved to an element inside a container with role="application", JAWS does not enter application mode. Tabbing to the next element inside the container will then enter application mode.

### Expected result
JAWS enters forms mode on focus of an element inside a container with role="application", regardless of how focus got there.

### Actual result
JAWS only enters forms mode if the focus is a result of user focus (tab, click). It sounds like JAWS enters application mode, then switches to browse mode and announces the element with focus.

### Example
Attached is an example (saved as .txt so I can attach it). On window load, focus moves to the link and is in virtual PC cursor mode. Tabbing to the button then changes to application mode.

[test.txt](https://github.com/FreedomScientific/VFO-standards-support/files/2120380/test.txt)

#### JAWS version and build number
18.0.5038

 
#### Operating System and version
Windows 10

#### Browser and version:
Google Chrome 67.0.3396.87
Electron 2.0.0

**Comment by corinnaSchultz** [comment] 2018-08-14 22:12
I found that (depending on the element that got the focus) if you press spacebar, then it goes into forms mode (you hear the "boop" sound).

**Comment by LJWatson** [comment] 2018-08-16 08:56
@tydunkel I think this is expected behaviour. When focus is moved using JS, Jaws will be in Virtual Cursor mode. Triggering applications mode from within virtual mode would be quite problematic in other circumstances.

@corinnaSchultz Pressing space is one way that Jaws can be forced into applications (or forms) mode. In this context, it has the same effect as using the tab key to move focus onto the element with `role="application`.

**Comment by corinnaSchultz** [comment] 2018-08-16 17:28
One thing I noticed while testing my code is that *sometimes* it goes into forms mode and sometimes it doesn't.

I have a div which is in a region. A child of that div is a button. When you press space bar on the button, it causes a div containing another div with role="application" to open, and the code puts the focus on an input field in the application area.

When I tab to the button and space bar, the application div almost always opens and goes into form mode with the focus in the right spot (and the label for the input is read correctly).

When I use R to go to the various regions, and end up on the toolbar region, and then hit spacebar, the button is activated (why, since the focus should be on the region div, not the button?) and the application div opens up, the focus goes to the input field, but jaws doesn't go into forms mode. I can press space to trigger forms mode.

I haven't had the time yet to try and create a simple reproducible example, but in the context of my code, this is pretty reliably reproducible.

**Comment by LJWatson** [comment] 2018-08-16 17:56
@corinnaSchultz This is the expected behaviour.

Applications mode is invoked by pressing the tab key to move into the application region, or by pressing the space or enter key when inside an application region. This post on [Understanding screen reader interaction modes](https://tink.uk/understanding-screen-reader-interaction-modes/) has more information on this.

**Comment by corinnaSchultz** [comment] 2018-08-16 18:34
I don't understand the inconsistency, though. if (case 1) you tab to the button and press space, vs. (case 2) Using R to go to the region then press space. Either way, you are invoking the application div to open, and the javascript is setting the focus in the text field inside the application. But in the first case, JAWS is going into forms mode, and in the second case, it doesn't.

The article you linked talks about tabbing to a field, or tabbing into an application. The use case I described isn't either of those situations. I don't really see references in the jaws docs about what happens when javascript puts the browser into various states. In case 2 above, when I press the NumPadPlus key, jaws says "virtual PC Cursor". The JAWS docs say "When the virtual cursor is active, JAWS enters forms mode upon encountering an edit field."

**Comment by LJWatson** [comment] 2018-08-16 18:48
I suspect the difference is that in your first example you're pressing space on the button, and in the second you're pressing space whilst Jaws' is focused on the region. It isn't clear why using the space key on the region activates the button, but it suggests the JS may be bubbling up to the button's container element for some reason.

**Closed** 2020-05-11 21:02 UTC
Labels: archive
