### ISSUE TITLE
Number 2 can no longer be used for heading navigation since JAWS 2019

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#214] opened 2019-07-11 03:01 UTC
### Summary

The numbers 1-6 can be used in JAWS to navigate to the headings with the level 1-6. Since JAWS 2019, the number 2 no longer works. However, Shift+2 can still be used to navigate backwards to the level 2 headings. 

Example:
1. https://www.w3.org/WAI/tutorials/page-structure/headings/
2. Press 2

### Expected result

Navigation to heading level 2

### Actual result

Nothing

### Example

https://www.w3.org/WAI/tutorials/page-structure/headings/

#### JAWS version and build number
JAWS 2019 (build number does not matter)
 
#### Operating System and version
Windows 7, Windows 10

#### Browser and version:
All browsers (Firefox, Chrome, IE 11, Edge...)

**Comment by scottaohara** [comment] 2019-07-11 12:51
Do you happen to have any other sort of OS/browser plugins on at the same time as JAWS?

Reviewing the example page you linked to, among others, on a windows 10 machine using Firefox, Chrome, IE11 and Edge, I can use the <kbd>2</kbd> key to navigate between any / all heading level 2s.

**Comment by JAWS-test** [comment] 2019-07-11 19:48
I do not use browser plugins and tried different OS. However, I use the German version of JAWS. Maybe the bug only exists in this version?

**Comment by scottaohara** [comment] 2019-07-11 20:01
interesting.  if we're both on default settings and language is the only difference, that could be it?

**Comment by LJWatson** [comment] 2019-07-12 07:44
I can confirm that the 2 key works as expected with the latest patch of Jaws 2019 on Windows 10 with Firefox 67, Chrome 75, and Edge 77.

I tried it on the W3C page given as the example, as well as [my blog](https://tink.uk]) and the [BBC News site](https://bbc.co.uk/news)

**Comment by JAWS-test** [comment] 2019-07-13 04:28
I have installed the English version of JAWS 2019. The problem does not occur. I.e. it is only a problem of the German version (and possibly other language versions).

**Comment by JAWS-test** [comment] 2019-07-13 06:33
I would greatly appreciate it if the problem is fixed because the headings navigation is the primary navigation to find the content, see: https://webaim.org/projects/screenreadersurvey7/#finding

**Comment by LJWatson** [comment] 2019-07-13 09:00
@JawsTest it will be difficult to solve this if no-one else can duplicate the problem. 

I've created a [simple test case](http://test-cases.tink.uk/headings/). The page just has an h1, some text, an h2, some text, another h2, and some text; all inside a body element.

The 2 key works almost as expected for me in Chrome, Edge beta, and Firefox; with one exception. The first time I press 2, Jaws announces the h1, followed by the h2. After that, the 2 key works as expected.

Can you test to see what you get, and @scottaohara also?

**Comment by StommePoes** [comment] 2019-07-13 09:13
I just ran both my Jawses. My Fusion version is 2019.1906.10 ILM English and Chrome-latest, Firefox-latest, IE11 and Edge-latest all did the right thing with the W3C headings test page (as well as this Github page).

To be sure I also checked a 2018 dedicated JAWS I have which defaults to Dutch and same: I can reliably go both forwards and backwards with (Shift+) "2". I dunno why I still have that version TBH.

**Comment by MarcoZehe** [comment] 2019-07-13 09:30
Confirmed for the German version. default.jkm is missing the line

2=MoveToNextHeadingLevelTwo

The line is simply not there.

**Comment by stevefaulkner** [comment] 2019-07-13 12:02
@MarcoZehe thanks for providing the details
I have filed an internal Bug 109940 - German version of JAWS - no heading level 2 navigation

@ggordon-vfo this looks like an easy fix.

**Comment by GermanLocalization** [comment] 2019-07-16 09:26
This problem only existed in JAWS builds created between 1st of April and 6th of May 2019. 
Latest JAWS Hotfix 2019.1906.10 already contains a fix for it, and does no longer miss the line 
2=MoveToNextHeadingLevelTwo
Please update your system to the June Hotfix Version, 2019.1906.10.
There is no need to add a bug for it, problem no longer exists when latest JAWS version is used.

**Comment by JAWS-test** [comment] 2019-07-16 09:37
@GermanLocalization: Thank you very much!

**Comment by MarcoZehe** [comment] 2019-07-16 09:58
@GermanLocalization Thank you, fix confirmed. Sorry about that, should have checked for the latest update first, but when I started JAWS to verify the bug over the weekend, I was not notified of the update automatically, so thought I was on the latest version. :)

**Comment by scottaohara** [comment] 2019-07-16 11:13
Closing as confirmed fixed in latest JAWS version, 2019.1906.10.

**Closed by scottaohara** 2019-07-16 11:13 UTC
Labels: Fixed in JAWS 2019, JAWS bug filed, bug
