### ISSUE TITLE
When JAWS is active, Some accessibility controls on Chrome is broken

### ISSUE THREAD

**Issue by emshedu** [FreedomScientific/VFO-standards-support#560] opened 2021-08-02 23:47 UTC
### Summary
Without JAWS running, keyboard accessibility features work as expected-- you can tab through the various controls and menus and use them with 'Enter' or the arrow keys. However, with JAWS running, some or all of these controls become unusable with keyboard controls on certain browsers.

> Brief description of the issue. Please list any specific steps.
> Please see Attached Video for demo:
Without JAWS activated, I am able to select an option from a dropdown list of option using arrow keys and enter button, navigate to the OK button and pressing enter
When JAWS is activated, the item from the list, even if it is selected, is not added. JAWS closes the dropdown dialog

### Expected result

> I do not expect JAWS to interfere with the current function of the web page.

### Actual result

> Chrome: it closes the dialog and without assigning the value
> Firefox: everything works fine
> Chromium Edge: it closes the dialog and without assigning the value

### Example

> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...

### Additional Information
JAWS
version 21

browsers
Reproduced with Chrome Version 92.0.4515.107, and Microsoft Edge Version 92.0.902.62 (couldn't reproduce at all with Firefox)

OSes
Tested on Windows 10 

[Test on Chrome without JAWS on.zip](https://github.com/FreedomScientific/VFO-standards-support/files/6920140/Test.on.Chrome.without.JAWS.on.zip)
[Test on Mozilla with JAWS on.zip](https://github.com/FreedomScientific/VFO-standards-support/files/6920141/Test.on.Mozilla.with.JAWS.on.zip)
[Test on Chrome with JAWS on.zip](https://github.com/FreedomScientific/VFO-standards-support/files/6920142/Test.on.Chrome.with.JAWS.on.zip)

**Comment by JAWS-test** [comment] 2021-08-03 06:02
In general, JAWS intercepts all keystrokes and uses them for itself or passes them on to the browser, but converts them if necessary (e.g. into a click event). However, if device-independent event handlers and the correct ARIA roles are used correctly, there are usually no problems. An analysis of the problem is only possible if there is access to the source code

**Comment by menovak** [comment] 2021-08-11 01:14
hi emshedu,

Again source code will be the only real way to track or figure this issue out but a suggestion?   

JAWS (like other screen readers) has multiple mode of operation.   In simple terms, there is Forms mode where you can TAB from active element (e.g., buttons) to active element and activate them.,  JAWS also has browse mode, when you literally arrow up/down the page contents and JAWS announces (e.g., reads) all the content like in browsing.   Keys are handled differently in each.

When JAWS switches modes, you should hear a subtle beep - a high pitch means you are in Forms mode, a low pitch is browse mode.   In browse mode, another way to think of it, is the PC cursor is on and you can navigate  from heading to heading by pressing the 'h' key.

I'm explaining all this as sometimes JAWS doesn't know what a custom element is (or if the code is incorrect JAWS has to guess) - or the custom control is exposed via the browser API slightly different (FF vs Chrome) - to suggest you make sure you try both modes when you find JAWS doing something weird like closing a dropdown list.  

It is easy to swap modes in JAWS, if press the Insert + z, you should hear the respective beep (high/low pitch) and JAWS will announce PC cursor off (Forms mode) or PC Cursor on (browse mode).    Check that out as I'm guessing if you get into the correct mode, JAWS will function correctly (passing keys or grabbing keys).

Good luck
Mark

**Closed** 2021-09-15 21:28 UTC

**Comment by menovak** [comment] 2021-09-15 21:33
Nothing from customer in 6 weeks - closing
