### ISSUE TITLE
Native form element not surfaced as landmark by JAWS 18 or 2018

### ISSUE THREAD

**Issue by scottaohara** [FreedomScientific/VFO-standards-support#52] opened 2018-02-20 15:48 UTC
### Summary

When attempting to navigate a document by landmark regions, I expected JAWS to navigate to forms on the page.  However, testing with JAWS 18 and 2018, this was not the case as native form elements are not being surfaced as landmark roles.

### Expected result

Expected that `form` elements would be exposed as a landmark and that froms could be navigated to via region quick keys.

### Actual result

Native form elements, and form elements with a set `aria-label` were not surfaced as landmark regions by JAWS 18 or 2018.  

However, JAWS 18 did surface a `div role="form"` in all browsers tested.  JAWS 2018 was similar, but did not surface the `role="form"` in latest Edge.

### Example

[Here is a test page](http://www.scottohara.me/testing/form/) for a native form element, a form element with a set `aria-label`, a `div[role="form"], and a control `contentinfo` landmark.  As noted in the results, this is not an issue unique to JAWS.

#### JAWS version and build number
JAWS 2018 - build 1712.10 
JAWS 18.0.4534

 
#### Operating System and version
Windows 10

#### Browser and version:
IE11, latest Chrome, latest Edge, Firefox ESR

**Comment by stevefaulkner** [comment] 2018-03-01 08:05
@scottaohara looks like the issue is due to Firefox (and chrome) not exposing the role correctly in the accessibility tree. 
Refer to mapping spec form with an accessible name
https://w3c.github.io/html-aam/#el-form
Can you file bugs on the browsers?

**Comment by stevefaulkner** [comment] 2018-03-01 10:50
@scottaohara got ball rolling with firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1442196

**Comment by scottaohara** [comment] 2018-03-05 14:51
[Submitted the bug to chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=818428&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=) over the weekend as well.

**Comment by stevefaulkner** [comment] 2018-03-13 15:49
closing as bugs have been filed

**Closed by stevefaulkner** 2018-03-13 15:49 UTC
Labels: Chome issue - bug filed, Chrome bug, Firefox bug, Firefox issue - bug filed
