### ISSUE TITLE
JAWS misidentifies a table as a display table

### ISSUE THREAD

**Issue by tmthywynn8** [FreedomScientific/VFO-standards-support#124] opened 2018-10-05 04:27 UTC
### Summary

Duplicate of #92 &mdash;where JAWS's heuristics misidentifies a table as a display table and does not allow for table navigation commands.

1. Go to the [Keyboard shortcuts for Microsoft Word on Windows](https://support.office.com/en-us/article/95ef89dd-7142-4b50-afb2-f762f663ceb2) support article.
2. Use T to jump to the first table of commands.

### Expected result

JAWS should say something similar to "start of table with 21 rows and 2 columns".

### Actual result

JAWS says that "there are no tables on this page".

### Example

The [Keyboard shortcuts for Microsoft Word on Windows](https://support.office.com/en-us/article/95ef89dd-7142-4b50-afb2-f762f663ceb2) support article, as well as the ones listing shortcuts for [Excel](https://support.office.com/en-us/article/1798d9d5-842a-42b8-9c99-9b7213f0040f), [Outlook](https://support.office.com/en-us/article/3cdeb221-7ae5-4c1d-8c1d-9e63216c1efd), [Powerpoint](https://support.office.com/en-us/article/5a0c6c2d-b2c4-4e53-aeae-62005dfe3c0d), and [Access](https://support.office.com/en-us/article/069fa421-3a51-4b92-8712-d324c623751f). Note that a similar resource&mdash;[Keyboard shortcuts in Windows](https://support.microsoft.com/en-us/help/12445) support article does not have this issue. This is possibly because each cell in the first list of examples has a paragraph tag surrounding its contents whereas the second resource does not do this.

#### JAWS version and build number

JAWS 2018.1808.10 English - August 2018

#### Operating System and version

Windows 10, Version 1803

#### Browser and version:

Mozilla Firefox 62.0.3

**Comment by ggordon-vfo** [comment] 2019-06-18 13:26
This works for me with the JAWS 2019 June 2019 update and Firefox 67,Chrome 71, and IE 11. Closing issue.

**Comment by lamador** [comment] 2020-05-12 17:46
Not reproducible using the latest version of JAWS 2020 (2020.2004.66) and Firefox (76.0.1 (64-bit))

**Closed by lamador** 2020-05-12 17:46 UTC
