### ISSUE TITLE
JAWS 18 Reads Labels inside a Modal Dialog Multiple Times

### ISSUE THREAD

**Issue by wizzyfx** [FreedomScientific/VFO-standards-support#6] opened 2017-10-08 23:23 UTC
### Summary

> On Internet Explorer 11, if a form element and a label are placed inside a container which has the role of "dialog", JAWS repeats the label, times the number of children nodes in the label, when the form element receives focus via Tab. i.e: Having two spans inside the label, makes it repeat the label twice, for three spans, it repeats three times and so on.

>This only happens when Tab is used for navigation. Both implicit and explicit labels are subject to the same bug. 

### Expected result

> Each child node should only be included once when calculating the label of an input.

### Actual result

> Each child node is included multiple times when calculating the label of an input.

### Example

> https://codepen.io/wizzyfx/pen/MoNVrP
> Screen Capture: https://streamable.com/g4biq

#### JAWS version and build number

> JAWS 18.0.4321
 
#### Operating System and version

> Windows 10 64-Bit

#### Browser and version:

> IE 11

**Comment by stevefaulkner** [comment] 2017-10-09 14:30
Thanks @wizzyfx , sounds annoying. have confirmed with JAWS 18.0.4321/IE11. Will file a bug.

**Comment by wizzyfx** [comment] 2017-10-09 20:39
Thanks @stevefaulkner, very much appreciated!

**Comment by stevefaulkner** [comment] 2017-10-09 22:21
@wizzyfx thanks for the issue report, internal bug filed:
Bug #96914 - JAWS 18 Reads Labels inside a Modal Dialog Multiple Times

**Comment by ljnacht** [comment] 2017-11-06 19:44
I'm having this exact problem as well but in addition to it, if there is a button inside the dialog and I tab to it, it will dictate part of the aria-labelledby and aria-describedby assigned to the dialog before it dictates the aria-label on the button. Here's the simplified structure of my dialog:

`<div role="dialog" aria-labelledby="dialogTitle" aria-describedby="dialogContent">
    <h1 id="dialogTitle"> Dialog Title </h1>
    <p id="dialogContent"> some content... </p>
    <button onclick="close()" role="button" aria-label="close"> Close </button>
</div>`

**Comment by joe-watkins** [comment] 2018-05-01 16:12
Any updates on this one? Feels like adding the `role="dialog"`, regardless of how many other attributes you throw at it (`aria-describedby`, aria-labelledby`, `aria-label`) and where focus points to, things get announced multiple times.

I remember in some JAWS release notes a while back something about "..if modals are coded correctly JAWS will do this..." That worried me then, and now I wonder if it is a contributor?

**Comment by stevefaulkner** [comment] 2018-05-01 20:17
@joe-watkins thanks for the ping, I tested again in Latest JAWS 2018 and the issue is still present. I looked at the internal bug i filed and it has been assigned, target for fix is in JAWS 2018, but minor version is not stated. I have added note about follow up, so hopefully this will push it along. Its a funny bug as I can get it to happen sometimes but not others, at least its IE only ;-). 
I created an updated test case https://s.codepen.io/stevef/debug/VxbZog

**Comment by scottaohara** [comment] 2019-03-06 16:46
Retesting the original codepen example and Steve's example today with IE11 + JAWS 2018 (latest build) and 2019 (latest build). 

Cannot reproduce the issue in either version.  Closing.

**Closed by scottaohara** 2019-03-06 16:46 UTC
Labels: Fixed in JAWS 2018, IE11, JAWS bug filed, bug

**Comment by danielFreitasExternal** [comment] 2023-09-27 15:12
> @joe-watkins thanks for the ping, I tested again in Latest JAWS 2018 and the issue is still present. I looked at the internal bug i filed and it has been assigned, target for fix is in JAWS 2018, but minor version is not stated. I have added note about follow up, so hopefully this will push it along. Its a funny bug as I can get it to happen sometimes but not others, at least its IE only ;-). I created an updated test case https://s.codepen.io/stevef/debug/VxbZog

The test case is definitely different from the author's original codepen... 
It misses the `role="dialog"` attribute in the "Test Dialog 2" `<div>` that wraps up the `<input>`s and `<label>`s

side note: when testing the author's original test case, I am able to note that only "Name Required" is repeated, and only when focus enters the dialog element. When navigating inside, behavior is as expected. I tested with the latest JAWS version in both updated Edge and Chrome, with same result.
