### ISSUE TITLE
Jaws 2018 & Chrome Select Option not announcing 

### ISSUE THREAD

**Issue by leandrasilver** [FreedomScientific/VFO-standards-support#149] opened 2018-12-11 21:55 UTC
### Summary

> Change of select options with the arrow keys are not announcing. 
Labels, and the default selected options, are announced though, just not the change of options. 

> 
> Example:
> 1. Go to https://codepen.io/leandrasilver/pen/xmGXom
> 2. Shift-Tab select menus.

### Expected result

> Options are announced on change.

### Actual result

> Everything seemingly works ok, but the change of options with the arrow keys, only on chrome.
> Works well with firefox

#### JAWS version and build number
Jaws 2018.1805.33 ILM

#### Operating System and version
Windows 10 Enterprise Version 1709

#### Browser and version:
Google Chrome: Version 71.0.3578.80 (Official Build) (64-bit)

**Comment by stevefaulkner** [comment] 2018-12-31 15:42
@leandrasilver  could not reproduce with JAWS 2019.182.49 and Chrome Version 71.0.3578.98 (Official Build) (64-bit) 
options announced as selected via arrow keys

**Comment by stevefaulkner** [comment] 2019-01-14 12:57
closing as cannot reproduce

**Closed by stevefaulkner** 2019-01-14 12:57 UTC
Labels: Under review, can't reproduce
