### ISSUE TITLE
JAWS doesn't narrate radiogroup name/label in dialog

### ISSUE THREAD

**Issue by kolaps33** [FreedomScientific/VFO-standards-support#694] opened 2023-01-25 10:55 UTC
### Summary 
When radiogroup widget is included in dialog, then JAWS doesn't narrate label of radiogroup. 

1.1 JAWS Virtual cursor mode is OFF  (when virtual cursor is ON then I could not repro the issue)
1.2 Go to https://codesandbox.io/s/stupefied-keldysh-m4xc99?file=/example.tsx:561-611
2. Navigate on button "open dialog"
3. Press enter key /// dialog is opened
4. Navigate into radio group 
5. observe JAWS narration ### Expected result
JAWS narrates radiogroup label ### Actual result
JAWS doesn't narrates radiogroup label 
### Example
Radiogroup in dialog: https://codesandbox.io/s/stupefied-keldysh-m4xc99?file=/example.tsx:561-611

### Additional Information 
When radiogroup is no in dialog, then JAWS narrates radiogroup name when user navigate to radio.
Please see this example: 
Radiogroup with no dialog: https://codesandbox.io/s/dreamy-bird-0zm1lu?file=/example.tsx  

#### JAWS version and build number
2023.2212.23 

#### Operating System and version 
    OS: Windows 10 10.0.22621

#### Browser and version:
Chrome Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by JAWS-test** [comment] 2023-01-25 11:29
I can't reproduce the error. For me, JAWS also outputs the label of the group in the dialog ("Favorite Fruit"). The important thing is that the group label is only output when entering the group and not for every single element within the group. This is desired standard behavior of screen readers

**Comment by stevefaulkner** [comment] 2023-06-17 22:08
closing as @JAWS-test cannot reproduce

**Closed by stevefaulkner** 2023-06-17 22:08 UTC
