### ISSUE TITLE
Everything inside a given li element is read out

### ISSUE THREAD

**Issue by ghristanov** [FreedomScientific/VFO-standards-support#22] opened 2017-11-15 14:38 UTC
### Summary

1.	Go to https://codepen.io/anon/pen/rYzEMo
2.	Press TAB until you reach the link

### Expected result

Only the text of the link (Test 1) is read out.

### Actual result

Everything inside the list item is read out. If the p tag in the example is replaced by span, label, etc. it would still be included.

### Example

https://codepen.io/anon/pen/rYzEMo

#### JAWS version and build number

18.0.4350, 16.0.4474
 
#### Operating System and version

Windows 10 Enterprise 10.0.14393 Build 14393

#### Browser and version:

Internet Explorer 11

**Comment by stevefaulkner** [comment] 2017-11-16 16:24
@ghristanov as i commented in #13 this is a result of the use of `role=application`. It would be good to better understand why you are using this role? As the use of role=application is [generally discouraged](https://w3c.github.io/using-aria/#using-application)

**Comment by ghristanov** [comment] 2017-11-22 08:50
@stevefaulkner I provided an answer in [#13](https://github.com/FreedomScientific/VFO-standards-support/issues/13). As I said there, this isn't something we will be able to change easily.

**Comment by stevefaulkner** [comment] 2017-12-07 15:22
@ghristanov  it would be useful to know how you are using role=application can you share a complete test case?

**Comment by JAWS-test** [comment] 2019-08-24 02:08
The problem no longer exists with JAWS 2019

**Comment by frex65** [comment] 2020-05-18 13:53
Still an issue in JAWS 2020.2004.06.

**Comment by BenKeyFSI** [comment] 2021-01-11 22:13
This is a duplicate of [Link is read multiple times when it is in a list](https://github.com/FreedomScientific/VFO-standards-support/issues/13).

The Link is read multiple times when it is in a list resulted in a JAWS bug being filed. This bug is fixed in JAWS 2021.  It was first available in 2021.2009.19.400.

Thus I am closing this issue.

**Closed by BenKeyFSI** 2021-01-11 22:13 UTC
Labels: IE11, More info needed, bug
