### ISSUE TITLE
Use of aria-pressed triggers manual forms mode

### ISSUE THREAD

**Issue by Wildebrew** [FreedomScientific/VFO-standards-support#4] opened 2017-10-06 12:51 UTC
### Summary

When a toggle button (a `<button>` element with an `aria-pressed` attribute) is activated while Jaws is running in manual forms mode, Jaws goes into forms mode (when button is pressed).

Forms mode is necessary in complex widgets where the author is responsible for keyboard navigation, but toggle buttons are not complex widgets, they act like checkboxes and toggling a checkbox does not trigger forms mode, neither does clicking a button.
Toggle buttons are frequently used to filter search results or as a replacement for a checkbox.

#### to reproduce
1. Rename the attached file to a .html extension and open in Firefox or Chrome (or open the Code pen , thanks Steve).
2. With Jaws running, switch to manual forms mode (in the browser, press Jaws-key and v, type "forms" in the search, locate "forms mode" by pressing arrow down, press spacebar until 'manual" is selected, then tab over to the "ok" button and confirm.
3. Navigate to and activate the "I agree button".
4. Forms mode is triggered (and Jaws announces "pressed').

If you activate the button in IE11 the pressed state is not announced automatically, (and the button is not announced as a "collapsed button".

#### Browsers
Tested with Firefox and chrome on Windows 8, IE11 does not expose the aria-pressed attribute.
[ariapressedtest.txt](https://github.com/FreedomScientific/VFO-standards-support/files/1362715/ariapressedtest.txt)

**Comment by stevefaulkner** [comment] 2017-10-06 13:01
Thanks @Wildebrew will look into it. I have created a [code pen](https://s.codepen.io/stevef/debug/jGZqOL) from your test case.

**Comment by stevefaulkner** [comment] 2017-10-06 13:48
@Wildebrew I tested it, but could not reproduce the forms mode issue. Testing with JAWS 16/17/18 + Firefox 56, JAWS 16/17/18 + Chrome 61, JAWS 16/17/18 + IE 11
**Notes:** 
* with IE11, when the button is pressed the change in state is not announced, but when the button is moved away from then refocused the 'pressed' state is correctly announced.
* tested using both `enter` and `space` keys to activate button. tested by navigating using both virtual cursor and `tab` key.

**Comment by LJWatson** [comment] 2017-10-06 15:59
I can confirm the behaviour described by @Wildebrew (using the Jaws 2018 public beta).

Note: the issue only occurs when Jaws uses the default manual forms mode, not when it uses semi-auto or auto forms mode.

**Comment by Wildebrew** [comment] 2017-10-06 16:20
Thank you Leonie
That was my mistake. I forgot to specify this only happens in the
manual forms mode setting.



On 10/6/17, Léonie Watson <notifications@github.com> wrote:
> I can confirm the behaviour described by @Wildebrew (using the Jaws 2018
> public beta).
>
> Note: the issue only occurs when Jaws uses the default manual forms mode,
> not when it uses semi-auto or auto forms mode.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/FreedomScientific/VFO-standards-support/issues/4#issuecomment-334797153


-- 
Work hard. Have fun. Make history.

**Comment by stevefaulkner** [comment] 2017-10-07 14:55
Internal bugs filed:
Bug 96893  JAWS does not announce updated aria-pressed state (in IE11)

**Comment by Wildebrew** [comment] 2017-10-07 16:32
I updated the issue description to include the manual forms mode setting.
I find it extremely distracting to have forms mode activated when I click that button, I often click it and continue to explore the page in browse mode. I hope it can be fixed as well.

**Comment by stevefaulkner** [comment] 2017-10-09 16:45
@Wildebrew wrote:
>Tested with Firefox and chrome on Windows 8

which browser versions?

**Comment by stevefaulkner** [comment] 2017-10-31 09:34
@Wildebrew has been fixed in internal build, will be coming down the pipe into public build sooner rather than later :-) Will keep issue open until fixed in public release.

**Comment by ChristAsselin** [comment] 2019-05-02 20:58
@stevefaulkner Do you know if the internal issue 96893 solved ? I would like to develop a push button with aria-pressed.

**Comment by ggordon-vfo** [comment] 2019-06-17 15:18
Both items work right for me in the JAWS 2019 June update. The manual forms mode portion got resolved some time back. Not exactly sure when JAWS started announcing Pressed after pressing the button in IE.

**Closed by ggordon-vfo** 2019-06-17 15:18 UTC
Labels: FIXED in JAWS 2018.next, JAWS bug filed, bug
