### ISSUE TITLE
interacting with a button inside <legend> causes focus to move to an input outside of fieldset

### ISSUE THREAD

**Issue by WickyNilliams** [FreedomScientific/VFO-standards-support#530] opened 2021-06-01 09:12 UTC
### Summary

If a `<button>` is placed inside a `<legend>`, interacting with the button will cause focus to move to a completely different `<input />`.

Consider this HTML:

```html
<form>
  <div>
    <label for="input1">Input 1</label>
    <input type="text" id="input1" name="input1" />
  </div>

  <fieldset>
    <legend>
      hello <button>world</button>
    </legend>
    
    <label for="firstName">First name</label>
    <input type="text" id="firstName" name="firstName" />

    <label for="lastName">Last name</label>
    <input type="text" id="lastName" name="lastName" />
  </fieldset>

  <button type="submit">Submit</button>
</form>
```

If you tab to the button and hit Enter, then focus is moved to `input1` in chrome and `firstName` in IE11. Furthermore, you cannot navigate to the button with the virtual cursor.

### Expected result

Button to be interactive and navigable as you would expect. Button is valid content for legend as described in the HTML spec https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element

### Actual result

Focus moves to an unrelated input, not navigable with virtual cursor

### Example

A codepen with the above HTML: https://codepen.io/WickyNilliams/pen/poeppdJ

#### JAWS version and build number

JAWS 2020.2008.24 ILM
 
#### Operating System and version

Windows 10 

#### Browser and version:

Chrome 90.0.4430.212 / IE 11

**Comment by JAWS-test** [comment] 2021-06-01 10:46
Duplicate of https://github.com/FreedomScientific/VFO-standards-support/issues/402

**Comment by WickyNilliams** [comment] 2021-06-01 11:42
Ah yes, I missed this point:

> The JAWS cursor remains on the previously focused element, so that when you operate the link, the previously focused element is operated instead of the link.

This seems to explain the behaviour I observed. Closing

**Closed** 2021-06-01 11:41 UTC
