### ISSUE TITLE
Jaws says 'not in a table' when element inside <td> receives the focus

### ISSUE THREAD

**Issue by yugu0114** [FreedomScientific/VFO-standards-support#447] opened 2020-09-25 09:25 UTC
### Summary

> We have similar structure like in this example (Example 1: Minimal Data Grid)
> 
> Example:
> 1. https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html
> 2. Press insert+z to switch off virtual pc cursor mode
> 3. When <a tabindex="0" href="#">Cash Deposit</a> receives the focus Jaws says 'not in a table'

### Expected result

> only text of the link is announced

### Actual result

> 'not in a table' is announced, but text of the link is not
[OFF1.zip](https://github.com/FreedomScientific/VFO-standards-support/files/5281820/OFF1.zip)

### Example

> https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html (Example 1: Minimal Data Grid)

#### JAWS version and build number
2020.2008.24 ILM

 
#### Operating System and version
Win 10

#### Browser and version:
IE: version 11.1082.18362.0/ Update versions 11.0.210 (KB4577010)

**Comment by frex65** [comment] 2021-01-18 13:30
Checked the provided W3C example using JAWS 2021.2012.48 with IE11, and also with Firefox 83, Chrome 87.0.4280.141 and Edge 87.0.664.75, and could not reproduce. It seems this issue has been fixed in JAWS 2021. Closing this issue.

**Closed by frex65** 2021-01-18 13:30 UTC
Labels: Fixed in JAWS 2021, IE11, Not a bug
