### ISSUE TITLE
Inputs for Spanish documents are read out in English instead of Spanish

### ISSUE THREAD

**Issue by bestuiexperience** [FreedomScientific/VFO-standards-support#188] opened 2019-04-02 22:36 UTC
### Summary

>Inputs for Spanish documents (where lang="es" are read out in English instead of Spanish)
> 
> Example:
> 1. https://jsbin.com/foniqakari/edit?html,css,js,output
> 2. Start typing a zip code. Notice that the zip code is read out in English.
> 3. Now backspace. The numbers are correctly read out in Spanish when backspacing.

### Expected result

> Expected the input to be read in Spanish both when entering data forward as well as when backspacing.

### Actual result

> Input was read in English when entering data forward, but in Spanish when backspacing.

### Example

https://jsbin.com/foniqakari/edit?html,css,js,output

#### JAWS version and build number

2019.1810.64 ILM

 
#### Operating System and version
Windows 10

#### Browser and version:
All - Chrome, Firefox, and IE11

**Comment by JasonAment** [comment] 2019-05-01 14:05
Hello, This happens when the "keyboard" language is set to English.  The Screen reader will respect the declared keyboard language of the **user** for the input, but will read the item back in the language of the **page**.  Changing the keyboard language to Español will resolve the issue.  The keyboard language can be set separately from the system language. Changing the system language setting may not change the keyboard setting.  This can be found in the system tray after a second language pack is installed (See screenshots below).
If your keyboard language is set to English, the input will be in english as you type.  When you change the language to Español, the input will report in español as you type.
![image](https://user-images.githubusercontent.com/16707962/57019253-d0b3d600-6bda-11e9-9d38-e43d93423357.png)
alternative: Screenshot of the keyboard language switcher in the system tray. It is currently set to English.
![image](https://user-images.githubusercontent.com/16707962/57020609-a49a5400-6bde-11e9-8be7-e20761ae50f0.png)
alternative: screenshot of the expanded language setting in the system tray.  English is currently selected.
NOTE: All major screen readers will read the values while inputting them in the user declared language of the keyboard.

**Comment by JasonAment** [comment] 2019-05-01 14:08
@bestuiexperience - Thanks for presenting this issue.  It prompted a lot of great discussion within the team. :)
Closing this as "not a bug" - by design.

**Closed by JasonAment** 2019-05-01 14:08 UTC
Labels: Not a bug
