### ISSUE TITLE
JAWS 18 repeats label in IE11 depending on child elements

### ISSUE THREAD

**Issue by erikconrad** [FreedomScientific/VFO-standards-support#81] opened 2018-05-09 19:49 UTC
### Summary

In JAWS 18 in IE11 if you enter forms mode and focus on a form element, JAWS will repeat the label based on how many child nodes the label has,

### Expected result

JAWS should just read the label HTML once like any other HTML

### Actual result

JAWS will read labels with multiple children multiple times

### Example

https://s.codepen.io/erikconrad/debug/xjYyoe/gaMeYJqjdqWM

### Additional Information
This is similar to this bug: https://github.com/FreedomScientific/VFO-standards-support/issues/6

#### JAWS version and build number

JAWS Version 18.0.5038
 
#### Operating System and version

Windows 10 Pro

#### Browser and version:
IE 11 Version 11.402.16299.0
Update Versions: 11.0.60 (KB4092946)

**Comment by scottaohara** [comment] 2018-05-14 16:16
Note working link to example: https://codepen.io/erikconrad/pen/xjYyoe

**Comment by Goopies** [comment] 2018-11-28 19:00
I'm also having this issue and not really sure how to fix it without a code overhaul. Perhaps this is a bug that will be fixed?

**Comment by stevefaulkner** [comment] 2018-11-28 19:36
@erikconrad, @Goopies I tested with IE11, JAWS 2019 and JAWS 2018.1802 could not reproduce issue in either.

**Comment by Goopies** [comment] 2018-11-28 19:50
Thanks Steve, I'll see if I can make a working example.

**Comment by Goopies** [comment] 2018-11-29 18:05
Hey @stevefaulkner Try this demo out. I'm using IE 11 and JAWS 2018

http://cssdeck.com/labs/full/teb56ykz

**Comment by Goopies** [comment] 2018-11-29 18:06
I'll be the first to say the structure of the HTML isn't optimal, I'm just working with legacy code.

**Comment by scottaohara** [comment] 2018-11-29 18:19
hey @Goopies 
a few questions
1. have you tried removing the role=checkbox?  that shouldn't be necessary with the type also being checkbox.
2. have you tried adding role=presentation to the spans within the label?

**Comment by Goopies** [comment] 2018-11-29 18:21
I'll give those a go now and report back.

**Comment by Goopies** [comment] 2018-11-29 18:29
Thanks guys! Appreciate it.

**Comment by stevefaulkner** [comment] 2018-11-29 22:42
@erikconrad, @Goopies If you remove the (redundant in this case as the [association is provided](https://www.w3.org/TR/html52/sec-forms.html#the-label-element) due to the `checkbox` being a child of the `label`) `for` attribute or move the `checkbox` outside the `label` (but use `for`) The issue goes away.

```
<label>
<input type="checkbox" id="checkbox_phxid2" value="orange">
<span></span>
<span>Orange</span>
</label>
```

```
<input type="checkbox" id="checkbox_phxid3" value="apple">
<label for="checkbox_phxid3">
<span></span>
<span>apple</span>
</label>
```

**Comment by Goopies** [comment] 2018-11-29 23:45
Very cool! Did not think to try that, thanks!

**Comment by Goopies** [comment] 2018-11-30 16:21
Hi @stevefaulkner it seems like removing the `for` attribute doesn't solve the duplicate reads. 
Moving the input outside the label DOES solve the issue as a workaround, but I feel like it should still work without having to do so.

I've updated the example to remove the 'for'

http://cssdeck.com/labs/full/teb56ykz

**Comment by stevefaulkner** [comment] 2018-11-30 18:57
@Goopies the test case you provided still has the for?
http://cssdeck.com/labs/full/teb56ykz

**Comment by Goopies** [comment] 2018-11-30 19:00
Odd, should be fixed now.

Did a double check with JAWS 2018 and it's still reading multiple times.

**Comment by Goopies** [comment] 2018-11-30 19:01
And IE 11 of course @stevefaulkner

**Comment by scottaohara** [comment] 2018-11-30 19:23
@Goopies @stevefaulkner i created additional test cases to see if some other combo might prove better results: http://cssdeck.com/labs/tffgy1h2

Per the OP issue being filed, label is read multiple times when using the tab key to navigate.  if navigating by virtual cursor, i did not experience the issue.  tried using aria-hidden=true for the empty span, and that actually resulted in jaws announcing no accessible name for the checkbox when it was tabbed to.

Testing with Edge, Firefox and Chrome JAWS does not announce the content multiple times.

So... clearly there's something quirky with how IE11 and JAWS are working together... i am unsure if it's actually an issue with JAWS, or IE11....

**Comment by stevefaulkner** [comment] 2018-11-30 23:09
@Goopies I could reproduce the issue with JAWS 2018/2019 and I agree it should not occur and you should not need to move the control outside the label element. The underlying issue with IE 11 is that it does not expose sufficient information in the accessibility layer so Screen readers need to hack the DOM in order to convey information to users, this does not always work as it should, such as this case.

I experiemented a bit further and found that adding `aria-label` on the `checkbox` stops the duplicate label announcement without any other code changes, [give it a try](https://codepen.io/stevef/pen/jQXoRG?editors=1010)

```
<label for="checkbox_phxid2">
<input type="checkbox" id="checkbox_phxid2" value="Orange" aria-label="Apple"> <span></span>
<span></span>
<span></span>
<span>Orange</span>
</label>
```

I will file an internal bug on JAWS, but in the meantime hope the workarounds help.

**Comment by Goopies** [comment] 2018-11-30 23:36
Thanks @stevefaulkner that does work!

No worries, the workaround is pretty much exactly what I was looking for as it solves the issue without changing elements around.

Thanks both of you guys for looking into this. Thanks for filing the bug report as well.

**Comment by scottaohara** [comment] 2019-03-06 18:17
Note that testing with IE11 and JAWS 2019 this is still an issue.

**Comment by fred7474** [comment] 2019-06-14 18:48
> Note that testing with IE11 and JAWS 2019 this is still an issue.

Hello, I have this same problem at my work.    An H1 label gets read out twice, but only with the TAB function, with arrow key it works exactly as we intended.   Does anyone have a case file# for that JAWS defect that was reported above?

**Comment by TPGJRogers** [comment] 2022-11-16 19:50
Issue pertained only to IE11. Closing.

**Closed by TPGJRogers** 2022-11-16 19:50 UTC
Labels: bug, Solution provided
