### ISSUE TITLE
Jaws does not communicate description list semantics in Chrome/Edge

### ISSUE THREAD

**Issue by Wildebrew** [FreedomScientific/VFO-standards-support#850] opened 2024-07-14 13:36 UTC
### Summary

Jaws (with Chrome / Edge) exposes an HTML description list (`<dl>` structure) as a series of lines with no semantics.
 
Example:
1. Navigate to this [Description list article from MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl)
2. Scroll down to the frame with the example

### Expected result

Ideal: Term and definition elements are identified, 

e.g.

Term: Beast of Bodman
Definition: A large feline inhabiting bodman moor.

At minimum:
the structure is exposed as nested unordered lists:

term in the level 1 list
definitions exposed as a nested list for each term.

### Actual results

The description list elements are announced as a series of lines with no semantics (like a series of paragraph or `<div>` elements).

You don't know they are coded as a document structure.

#### JAWS version and build number

I am seeing this with Jaws 2023 and Jaws 2024, including the most recent update (as of July 14 2024) with Chrome and Edge (latest versions).

The situation is better in Firefox:

* the description list structure is announced as "description list"
* Each term/definition(s) pair is exposed as a list item

### Browser and version

Fails with latest build of Chrome and Edge
Works with latest build of Firefox

**Comment by JAWS-test** [comment] 2024-07-15 04:31
The definition lists are no longer recognised as lists. It is also not possible to navigate to the lists using L or I. The problem seems to be new, because in the past there was no correct distinction between dt and dd, but the list and the list entries were recognisable with JAWS (see https://github.com/FreedomScientific/standards-support/issues/157). Since this no longer works with old JAWS versions (e.g. JAWS 2018, JAWS 2020), with which it used to work, I suspect that the error lies with Chrome. Firefox transmits the list as DefinitionList, Chrome as DescriptionList, HTML AAM says that the role should simply be list - can this be the cause? However, the fact that NVDA can output the list as a list in Chrome speaks against this

**Comment by JAWS-test** [comment] 2024-07-15 08:57
I have now looked at the output to the API not only in the devtools but also with Accessibility Insights. There you can see that Chrome transmits a list but no list entries, in Firefox a list and list entries are transmitted. So in my opinion it is not a JAWS error, but a Chrome error that no list is recognised at all.

**Comment by stevefaulkner** [comment] 2024-07-28 16:10
closing as per @JAWS-test comments (with thanks)

**Closed as completed by stevefaulkner** 2024-07-28 16:10 UTC
Labels: triaged

**Comment by JAWS-test** [comment] 2024-07-28 17:37
@Wildebrew Please open a ticket at https://issues.chromium.org/issues and copy the link into this ticket

**Comment by LaurenceRLewis** [comment] 2024-10-01 06:25
If a bug was raised with chromium can someone post the link as I cannot find it through searching in the repository. Thanks.

**Comment by LaurenceRLewis** [comment] 2024-12-10 03:31
https://issues.chromium.org/issues/376278217
