### ISSUE TITLE
The Output element is not output as Live Region (IE 11, Firefox)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/VFO-standards-support#268] opened 2019-08-31 04:33 UTC
### Summary

The Output element is not output as Live Region (IE 11, Firefox)

1. Save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>output</title>
	</head>
	<body>
		<output id=1>
		</output>
		<button onClick="document.getElementById('1').innerHTML='live region';">add text</button>
		<button onClick="document.getElementById('1').innerHTML='<h2>live region</h2>';">add h2 and text</button>
	</body>
</html>
```
2. Activate the buttons one after the other

### Expected result
The Output element is output as Live Region (due to implicit role=status)

### Actual result
* The Output element is not output as Live Region (IE 11, Firefox)
* Works in Chrome 

See also https://github.com/w3c/aria-practices/issues/78 and many other problems with live regions: https://github.com/FreedomScientific/VFO-standards-support/issues?q=live+region

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2
Internet Explorer 11.0.9600.19431

**Comment by scottaohara** [comment] 2019-08-31 11:18
This is not a bug with JAWS, JAWS supports `role=status`.  Rather this is a bug with Firefox not having implemented `output` as a live region.  

I've filed a bug with Firefox about this already and its being worked on.

**Comment by stevefaulkner** [comment] 2019-08-31 15:07
closing as not a JAWS bug

**Closed by stevefaulkner** 2019-08-31 15:07 UTC
Labels: Firefox issue - bug filed, IE11

**Comment by zcorpan** [comment] 2019-09-02 16:32
The Firefox bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1563598

As far as I can tell (checking browser devtools), Safari and Chrome correctly map `output` to `role=status`

**Comment by scottaohara** [comment] 2019-11-21 23:34
Note: the linked bug has been marked as resolved and testing with Firefox nightly, `output` is mapped to the same platform roles as `role=status`
